version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      - "9000"  # Wewnętrzny port dla FPM, używany tylko przez nginx
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Aplikacja będzie dostępna pod localhost:8080
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
